name: Create packages WSA with Magisk and GAPPS

on:
  push:
    branches:
      - main

jobs:
  build_WSA:
    name: Create packages WSA with Magisk and GAPPS
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        repository: LSPosed/MagiskOnWSALocal

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt install -y lzip wine winetricks patchelf e2fsprogs aria2 python3 python3-pip aria2 p7zip-full attr unzip

    - name: Run.sh 
      run: |
        cd scripts
        ./run.sh

    - name: Package build artifacts
      run: |
        7z a test.7z *
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: test.7z
        path: test.7z
